use std::error::Error;

pub fn part1(input: &str) -> Result<String, Box<dyn Error>> {
    Ok("great job".into())
}

pub fn part2(_input: &str) -> Result<String, Box<dyn Error>> {
    Ok("great job".into())
}
